/// <reference types="node" />
// Prisma configuration for KISAN SAHAY Backend
// This file was generated by Prisma and customized for our needs

import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] || "file:./dev.db",
  },
});
